### ISSUE TITLE
Terraform Docker provider coverage

### ISSUE THREAD

**Issue by ryane** [joyent/triton-terraform#18]
I'd like to establish what kind of coverage we want to reach for Docker in Terraform. I made a little breakdown of what options you can control when creating containers in the Joyent UI vs what exists in the existing [Terraform provider](https://terraform.io/docs/providers/docker/r/container.html). Obviously, this is not a complete list and there is more you can control with the API/CLI but there are already notable gaps between what the Terraform provider offers so I figure this is a good place to start.

 Triton                         | Terraform         | Notes                                         
--------------------------------|-------------------|-----------------------------------------------
 Container Name                 | name              |                                               
 Data Center                    | DOCKER_HOST       |                                               
 Image                          | image (id)        |                                               
 Restart Policy                 |                   |                                               
 Attach Public IP (publish-all) | publish_all_ports |                                               
 Ports                          | ports             |                                               
 Volumes                        | volumes           | testing needed, probably limitations here     
 Labels                         |                   |                                               
 Links                          | links             |                                               
 Entrypoint                     |                   |                                               
 Command                        | command           |                                               
 Env                            | env               |                                               
 Network                        |                   |                                               
 Memory                         |                   |                                               
 CPU                            |                   |                                               
 Disk                           |                   | not sure how this is specified in the api yet 

Filling in most of these gaps will require changes to the Terraform provider. The other option, I suppose, would be to create a new resource (`triton_docker_container` maybe?). If it is feasible, though, I tend to think that enhancing the existing provider would be preferable. 

What do you guys think?

**Comment by ryane** [comment]
terraform v0.6.9 with the updated docker provider was released today! this can probably be closed at this point.

**Comment by xer0x** [comment]
Awesome!
