### ISSUE TITLE
triton-terraform does not ensure a resource is destroyed before recreating it

### ISSUE THREAD

**Issue by chorrell** [joyent/triton-terraform#25]
Whenever I make a change to a resource which requires it to be destroyed and then provisioned again I hit this issue:

```
* triton_machine.centos-6-builder-us-east-1: failed to create machine with name: centos-6-builder-us-east-1
caused by: Missing parameters https://us-east-1.api.joyent.com/joyentsoln/machines
caused by: request "https://us-east-1.api.joyent.com/joyentsoln/machines" returned unexpected status 409 with body "{\"code\":\"ValidationFailed\",\"message\":\"Invalid VM parameters: Invalid machine name\",\"errors\":[{\"field\":\"alias\",\"code\":\"Duplicate\",\"message\":\"Already exists for this owner_uuid\"}]}"

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

The Joyent CloudAPI doesn't allow you to have two machines in a DC with the same name. I think what's happening is that the provision step is happening too quickly after the resource is destroyed. Ideally triton-terraform should check the state of a resource to ensure it's destroyed before recreating it

**Comment by xer0x** [comment]
@chorrell try again today. The updates deployed today to JPC may contain a fix for this.

**Comment by chorrell** [comment]
Yes, looks like I'm not hitting this anymore. Closing!
